# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Raised Face Weld Neck Flange', kernelModule='FlangeWithBoltHolesMacro', kernelFunction='FlangeWithBoltHoles', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Raised Face:', keyword='raisedFace', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Raised Face Outer Diameter:', keyword='raisedFaceOD', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Flange Outer Diameter:', keyword='flangeOD', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Bolt Circle Diameter:', keyword='boltCircleD', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='# of Bolt Holes:', keyword='boltHoles', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Bolt Diameter', keyword='boltD', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Flange Thickness:', keyword='flangeThickness', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Hub Diameter:', keyword='hubD', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Pipe Outer Diameter:', keyword='pipeOD', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Length Through Hub:', keyword='hubLength', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Pipe Inner Diameter:', keyword='pipeID', default='')
dialogBox.show()